import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Nunito_Sans, Sassy_Frass } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const nunito = Nunito_Sans({ subsets: ["latin"], weight: ['400', '800', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className} style={{
        background: "linear-gradient(176deg,rgb(18,24,27) 50%,rgb(32,39,55) 100%)",
        minHeight: "100vh"
      }}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
